#!/bin/bash

set -e

doc="${1}"
out="${2}"
doc_noext="$(basename ${doc%.*})"

cd "${out}"

[ -e "${doc_noext}.synctex.gz" ] && is_gzip=true || is_gzip=false

if ${is_gzip}; then
  gunzip "${doc_noext}.synctex.gz"
fi

sed -i "2c Input:1:${doc}" "${doc_noext}.synctex"

if ${is_gzip}; then
  gzip "${doc_noext}.synctex"
fi
